# Test values file for CDK implementation
metadata:
  name: "test-service"
  version: "1.0.0"
  description: "Test service for values file implementation"

infrastructure:
  vpc:
    id: "vpc-12345678"
    subnets: ["subnet-12345678", "subnet-87654321"]

cluster:
  name: "test-cluster"
  containerInsights: true

taskDefinition:
  type: "FARGATE"
  cpu: 256
  memory: 512
  runtimePlatform:
    cpuArchitecture: "X86_64"
    os: "LINUX"
  containers:
    - name: "app"
      image: "nginx:alpine"
      portMappings:
        - containerPort: 80
          protocol: "tcp"

service:
  type: "LOAD_BALANCED"
  desiredCount: 1

loadBalancer:
  type: "APPLICATION"
  protocol: "HTTP"
  port: 80
  targetGroup:
    healthCheckPath: "/"

autoScaling:
  enabled: false

addons:
  logging:
    driver: "awslogs"
    retentionDays: 7 