# values-legacy-test.yaml - Test file in legacy flat format
# This tests backward compatibility with existing flat configuration

# Infrastructure configuration
vpcId: vpc-42de9927
subnetIds: subnet-c56802b2,subnet-103d3874
clusterName: test-cluster

# Container configuration
image: nginx:alpine
containerPort: 80
lbPort: 80

# Service configuration
stackName: test-service
desiredCount: 1
cpu: 256
memory: 512

# Load balancer configuration
publicLoadBalancer: true
lbProtocol: HTTP

# Health check configuration
healthCheckPath: /
healthCheckGracePeriodSeconds: 60

# Environment variables
environment:
  NODE_ENV: test
  TEST_VAR: test-value

# Logging
logRetentionDays: 7

# Auto scaling (optional)
enableAutoScaling: false
minCapacity: 1
maxCapacity: 3
targetCpuUtilization: 70
targetMemoryUtilization: 70 