# values-matsonlabs.yaml for cas-erd-svc deployment (Private IP Only)
# Values extracted from matsonlabs environment in cdk.json
# IAM permissions based on existing CDK stack implementation

# Infrastructure configuration
vpcId: vpc-42de9927
subnetIds: subnet-103d3874,subnet-c56802b2
clusterName: cas-erd-svc-cluster

# Container configuration
image: 275416279984.dkr.ecr.us-west-2.amazonaws.com/cas-erd-svc:2.0.0
containerPort: 8080
lbPort: 80

# Service configuration
stackName: cas-erd-svc
desiredCount: 1
cpu: 512
memory: 1024

# Load balancer configuration (Private IP only)
healthCheckPath: /casreferenceservice/  # Health check endpoint from existing CDK
allowedCidr: 10.120.0.0/24  # CIDR from existing CDK configuration

# Auto scaling (optional)
enableAutoScaling: true
minCapacity: 1
maxCapacity: 2
targetCpuUtilization: 70
targetMemoryUtilization: 70

# Logging
logRetentionDays: 30

# Environment variables (matching existing CDK configuration)
environment:
  APP_ENV: dev
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGION: us-west-2
  AWS_SDK_LOAD_CONFIG: "1"
  AWS_ENABLE_ENDPOINT_DISCOVERY: "true"

# Secrets (if needed)
secrets:
  # Database secret from matsonlabs environment
  DATABASE_URL: arn:aws:secretsmanager:us-west-2:275416279984:secret:dev/database/matx01/cas-apps/casuser-F2mG3y

# Advanced Features (optional)
# Service Discovery
serviceDiscovery:
  namespace: caserd.local
  serviceName: cas-erd-svc
  dnsType: A
  ttl: 60

# IAM Permissions Configuration
taskRolePermissions:
  secretsManager:
    actions:
      - secretsmanager:GetSecretValue
      - secretsmanager:DescribeSecret
      - secretsmanager:GetResourcePolicy
      - secretsmanager:ListSecretVersionIds
      - secretsmanager:ListSecrets
    resources:
      - arn:aws:secretsmanager:us-west-2:275416279984:secret:*
  cloudWatchLogs:
    actions:
      - logs:CreateLogGroup
      - logs:CreateLogStream
      - logs:PutLogEvents
      - logs:DescribeLogStreams
    resources:
      - "*"
  kms:
    actions:
      - kms:Decrypt
      - kms:DescribeKey
    resources:
      - arn:aws:kms:us-west-2:275416279984:key:*
  sts:
    actions:
      - sts:AssumeRole
    resources:
      - "*"
  # Additional commonly needed permissions for application tasks
  s3:
    actions:
      - s3:GetObject
      - s3:PutObject
      - s3:DeleteObject
      - s3:ListBucket
    resources:
      - arn:aws:s3:::my-app-bucket
      - arn:aws:s3:::my-app-bucket/*
  sqs:
    actions:
      - sqs:SendMessage
      - sqs:ReceiveMessage
      - sqs:DeleteMessage
      - sqs:GetQueueAttributes
    resources:
      - arn:aws:sqs:us-west-2:275416279984:*
  dynamodb:
    actions:
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
      - dynamodb:Query
      - dynamodb:Scan
    resources:
      - arn:aws:dynamodb:us-west-2:275416279984:table/*
  rds:
    actions:
      - rds-db:connect
    resources:
      - arn:aws:rds-db:us-west-2:275416279984:dbuser:*
  cloudWatchMetrics:
    actions:
      - cloudwatch:PutMetricData
    resources:
      - "*"

taskExecutionRolePermissions:
  secretsManager:
    actions:
      - secretsmanager:GetSecretValue
    resources:
      - arn:aws:secretsmanager:us-west-2:275416279984:secret:*
  cloudWatchLogs:
    actions:
      - logs:CreateLogStream
      - logs:PutLogEvents
    resources:
      - "*"
  ecr:
    actions:
      - ecr:GetAuthorizationToken
      - ecr:BatchCheckLayerAvailability
      - ecr:GetDownloadUrlForLayer
      - ecr:BatchGetImage
    resources:
      - "*"
  ssm:
    actions:
      - ssm:GetParameters
      - ssm:GetParameter
    resources:
      - "*"
  kms:
    actions:
      - kms:Decrypt
      - kms:DescribeKey
    resources:
      - arn:aws:kms:us-west-2:275416279984:key:*
  sts:
    actions:
      - sts:AssumeRole
    resources:
      - "*" 