# Development Environment Values
# Usage: cdk deploy --values examples/values-dev.yaml

vpcId: vpc-12345678
subnetIds: 
  - subnet-12345678
  - subnet-87654321
clusterName: dev-cluster
image: nginx:alpine
serviceName: dev-api
desiredCount: 1
cpu: 256
memory: 512
containerPort: 80
lbPort: 80
healthCheckPath: /
allowedCidr: 10.0.0.0/8
logRetentionDays: 7
enableAutoScaling: false
environment:
  NODE_ENV: development
  API_VERSION: v1
  LOG_LEVEL: debug
secrets: {} 