# Production Environment Values
# Usage: cdk deploy -c valuesFile=examples/values-prod.yaml

vpcId: vpc-87654321
subnetIds: 
  - subnet-87654321
  - subnet-12345678
clusterName: prod-cluster
image: 123456789012.dkr.ecr.us-west-2.amazonaws.com/myapp:latest
serviceName: prod-api
desiredCount: 3
cpu: 1024
memory: 2048
containerPort: 8080
lbPort: 80
healthCheckPath: /health
allowedCidr: 10.0.0.0/8
logRetentionDays: 30
enableAutoScaling: true
minCapacity: 2
maxCapacity: 10
targetCpuUtilization: 70
targetMemoryUtilization: 70
environment:
  NODE_ENV: production
  API_VERSION: v1
  LOG_LEVEL: info
secrets:
  DB_PASSWORD: arn:aws:secretsmanager:us-west-2:123456789012:secret:db-password-abc123
  API_KEY: arn:aws:secretsmanager:us-west-2:123456789012:secret:api-key-def456 