AWSTemplateFormatVersion: "2010-09-09"
Description: "Simple ECS Deployment Template for Testing"

Parameters:
  VpcId:
    Type: String
    Description: "VPC ID where the ECS service will be deployed"
    AllowedPattern: '^vpc-[a-z0-9]+$'

  SubnetIds:
    Type: CommaDelimitedList
    Description: "Subnet IDs for ECS service deployment"

  ClusterName:
    Type: String
    Default: "ecs-cluster"
    Description: "Name of the ECS cluster"

  ContainerImage:
    Type: String
    Description: "Container image URI"

  ContainerPort:
    Type: Number
    Default: 80
    Description: "Port that the container exposes"

  ServiceName:
    Type: String
    Default: "ecs-service"
    Description: "Name of the ECS service"

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ClusterName

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      VpcId: !Ref VpcId
      Subnets: !Ref SubnetIds
      Name: !Ref ServiceName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref ServiceName
      Cpu: "256"
      Memory: "512"
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Ref ServiceName
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              Protocol: tcp

Outputs:
  ClusterName:
    Description: "ECS Cluster Name"
    Value: !Ref ClusterName

  ServiceName:
    Description: "ECS Service Name"
    Value: !Ref ServiceName 